/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colores.vista;

import colores.modelo.ModeloColores;

/**
 *
 * @author daniel
 */
public class VistaColores extends javax.swing.JPanel {
    private ModeloColores mimodelo;
    private ControladorColores micontrol;
    
    /**
     * Creates new form VistaColores
     */
    public VistaColores() {
        initComponents();
        mimodelo = new ModeloColores();
        micontrol = new ControladorColores(this, mimodelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_R = new javax.swing.JTextField();
        txt_G = new javax.swing.JTextField();
        txt_B = new javax.swing.JTextField();
        bot_Salir = new javax.swing.JButton();
        bot_Convertir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_Hex = new javax.swing.JTextField();

        jLabel1.setText("R");

        jLabel2.setText("G");

        jLabel3.setText("B");

        txt_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RActionPerformed(evt);
            }
        });

        bot_Salir.setText("Salir");
        bot_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_SalirActionPerformed(evt);
            }
        });

        bot_Convertir.setText("Convertir");
        bot_Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_ConvertirActionPerformed(evt);
            }
        });

        jLabel4.setText("Hex");

        txt_Hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bot_Convertir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bot_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Hex, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(txt_R, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_G, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_B, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Hex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot_Salir)
                    .addComponent(bot_Convertir))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RActionPerformed

    private void txt_HexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HexActionPerformed

    private void bot_ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_ConvertirActionPerformed
        // TODO add your handling code here:
        micontrol.convertir();
    }//GEN-LAST:event_bot_ConvertirActionPerformed

    private void bot_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_SalirActionPerformed
        // TODO add your handling code here:
        micontrol.salir();
    }//GEN-LAST:event_bot_SalirActionPerformed

    public int getTextR (){
        return Integer.valueOf(txt_R.getText());
    }
    
    public int getTextG (){
        return Integer.valueOf(txt_G.getText());
    }
        
    public int getTextB (){
        return Integer.valueOf(txt_B.getText());
    }
    
    public void actualiza (){
        txt_Hex.setText(mimodelo.getHexadecimal());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot_Convertir;
    private javax.swing.JButton bot_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_B;
    private javax.swing.JTextField txt_G;
    private javax.swing.JTextField txt_Hex;
    private javax.swing.JTextField txt_R;
    // End of variables declaration//GEN-END:variables
}
