package reservahotel.vista;

import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.UIManager;
import static reservahotel.ConstantesError.*;
import reservahotel.modelo.Reserva;

/**
 * @author Daniel González Alonso
 * @author Daniel Paredes Santamaría
 */
public class DatosVista extends javax.swing.JFrame {
    private DatosControlador micontrol;
    private Reserva mimodelo;
    
    public DatosVista(Reserva mimodelo) {
        this.mimodelo = mimodelo;
        micontrol = new DatosControlador(this, this.mimodelo);
        
        initComponents();
        actualiza();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiq_Nombre = new javax.swing.JLabel();
        etiq_Apellidos = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        etiq_Pais = new javax.swing.JLabel();
        txt_pais = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        etiq_email = new javax.swing.JLabel();
        etiq_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        etiq_NombreTarj = new javax.swing.JLabel();
        etiq_NumeroTarj = new javax.swing.JLabel();
        etiq_Fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_numTarjeta = new javax.swing.JTextField();
        txt_propietario = new javax.swing.JTextField();
        txt_CVC = new javax.swing.JTextField();
        combo_mes = new javax.swing.JComboBox();
        etiq_barra = new javax.swing.JLabel();
        combo_año = new javax.swing.JComboBox();
        boton_Cancelar = new javax.swing.JButton();
        boton_Confirmar = new javax.swing.JButton();
        etiq_mensajeError = new javax.swing.JLabel();
        boton_Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reserva Hotel");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanel1.setToolTipText("");

        etiq_Nombre.setText("Nombre");

        etiq_Apellidos.setText("Apellidos");

        etiq_Pais.setText("País");

        etiq_email.setText("Email");

        etiq_telefono.setText("Teléfono");

        txt_telefono.setToolTipText("Campo de 9 dígitos para el número de teléfono.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiq_Nombre)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiq_Apellidos)
                            .addComponent(etiq_Pais)
                            .addComponent(etiq_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_apellidos)
                            .addComponent(txt_email)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 83, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiq_telefono)
                        .addGap(18, 18, 18)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_Nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_Apellidos)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_Pais)
                    .addComponent(txt_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiq_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Bancarios"));

        etiq_NombreTarj.setText("Propietario de Tarjeta");

        etiq_NumeroTarj.setText("Número de Tarjeta");

        etiq_Fecha.setText("Fecha de Expiración");

        jLabel4.setText("CVC/CVV/CID");

        txt_numTarjeta.setToolTipText("Campo de 14 dígitos para el número de Tarjeta.");

        txt_CVC.setToolTipText("Campo de 3 dígitos para el CVC.");

        combo_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));

        etiq_barra.setText("/");

        combo_año.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(etiq_NombreTarj)
                        .addGap(18, 18, 18)
                        .addComponent(txt_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiq_NumeroTarj)
                            .addComponent(jLabel4)
                            .addComponent(etiq_Fecha))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(combo_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiq_barra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_CVC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_NombreTarj)
                    .addComponent(txt_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_NumeroTarj)
                    .addComponent(txt_numTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_Fecha)
                    .addComponent(combo_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiq_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_CVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boton_Cancelar.setText("Cancelar");
        boton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CancelarActionPerformed(evt);
            }
        });

        boton_Confirmar.setText("Confirmar");
        boton_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ConfirmarActionPerformed(evt);
            }
        });

        boton_Atras.setText("← Atrás");
        boton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(boton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(boton_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiq_mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(boton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boton_Cancelar, boton_Confirmar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(boton_Atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiq_mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Cancelar)
                    .addComponent(boton_Confirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {boton_Cancelar, boton_Confirmar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AtrasActionPerformed
        micontrol.atras();
    }//GEN-LAST:event_boton_AtrasActionPerformed

    private void boton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CancelarActionPerformed
        micontrol.cancelar();
    }//GEN-LAST:event_boton_CancelarActionPerformed

    private void boton_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ConfirmarActionPerformed
        micontrol.confirmar();
    }//GEN-LAST:event_boton_ConfirmarActionPerformed

    /**
     * Método que comprueba si el texto que se le pasa puede convertirse a 
     * entero.
     * @return true si sí se puede convertir a entero.
     */
    private boolean checkTipo (String texto){
        try {
            Integer.parseInt(texto);
            return true;
        } catch (NumberFormatException e1){
            try {
                Long.parseLong(texto);
                return true;
            } catch (NumberFormatException e2) { 
                return false;
            }
        }
    }
    
    // Getters
    /**
     * @return el valor del campo Nombre en la vista.
     */
    public String getNombre() {
        return txt_nombre.getText();
    }
    
    /**
     * @return el valor del campo Apellidos en la vista.
     */
    public String getApellidos() {
        return txt_apellidos.getText();
    }
       
    /**
     * @return el valor del campo Pais en la vista.
     */
    public String getPais() {
        return txt_pais.getText();
    }
    
    /**
     * @return el valor del campo Email en la vista.
     */
    public String getEmail() {
        return txt_email.getText();
    }
    
    /**
     * @return el valor del numero de telefono en la vista, si los datos
     * no se pudieron convertir a un numero retornará ERRORGEN.
     */
    public int getTelefono(){
        String texto = txt_telefono.getText();
        if (checkTipo(texto)) {
            return Integer.parseInt(texto);
        } else {
            return ERRORGEN;
        }
    }
    
    /**
     * @return el valor del campo Propietario de Tarjeta en la vista.
     */
    public String getNombrePropietario() {
        return txt_propietario.getText();
    }
    
    /**
     * @return el valor del numero de tarjeta en la vista, si los datos
     * no se pudieron convertir a un long retornará ERRORGEN.
     */
    public long getNumeroTarjeta() {
        String texto = txt_numTarjeta.getText();
        if (checkTipo(texto)) {
            return Long.parseLong(texto);
        } else {
            return ERRORGEN;
        }
    }
    
    /**
     * @return el valor del Mes de Caducidad en la vista.
     */
    public int getMesCaducidad() {
         return combo_mes.getSelectedIndex();
    }
    
    /**
     * @return el valor del Año de Caducidad en la vista.
     */
    public int getAñoCaducidad() {
         return (Integer.parseInt(combo_año.getSelectedItem().toString()));
    }
    
    /**
     * @return el valor del campo CVC en la vista.
     */
    public int getCVC() {
        String texto = txt_CVC.getText();
        if (checkTipo(texto)) {
            return Integer.parseInt(texto);
        } else {
            return ERRORGEN;
        }
    }
    
    //Metodos para cambiar los colores en caso de Error
    /**
     * Método que pone el el objeto de la interfaz seleccionado al color por
     * defecto de la interfaz (color de correcto).
     * @param objeto que queremos cambiar de color.
     */
    public void colorDefecto (JComponent objeto){
        objeto.setBackground(UIManager.getColor ("Panel.background"));
    }
    
    /**
     * Método que pone el objeto de la interfaz seleccionado a rojo 
     * (color de incorrecto).
     * @param objeto que queremos cambiar de color.
     */
    public void colorError (JComponent objeto){
        objeto.setBackground(Color.red);
    }
    
    /**
     * Método que muestra un mensaje en caso de que se produzca la reserva
     * con éxito.
     */
    public void mensajeCorrecto (){
        etiq_mensajeError.setText("Reserva amacenada con éxito.");
        etiq_mensajeError.setBackground(Color.green);
    }
    
    /** 
     * Método que cambia a rojo el TextField e imprime un mensaje en caso de 
     * error y el color por defecto si no hay error en cada caso correspondiente.
     */
    public void error (boolean[] errores){
        etiq_mensajeError.setText("");
        boolean flag = false;
        
        if (errores[NOMBRE]){
            colorError(txt_nombre);
            flag = true;
        } else { colorDefecto(txt_nombre); }
        
        if (errores[APELLIDOS]){
            colorError(txt_apellidos);
            flag = true;
        } else { colorDefecto(txt_apellidos); }
        
        if (errores[PAIS]){
            colorError(txt_pais);
            flag = true;
        } else { colorDefecto(txt_pais); }
        
        if (errores[EMAIL]){
            colorError(txt_email);
            flag = true;
        } else { colorDefecto(txt_email); }
        
        if (errores[TELEFONO]){
            colorError(txt_telefono);
            flag = true;
        } else { colorDefecto(txt_telefono); }
        
        if (errores[PROPTARJETA]){
            colorError(txt_propietario);
            flag = true;
        } else { colorDefecto(txt_propietario); }
        
        if (errores[NUMTARJETA]){
            colorError(txt_numTarjeta);
            flag = true;
        } else { colorDefecto(txt_numTarjeta); }
        
        if (errores[CTECVC]){
            colorError(txt_CVC);
            flag = true;
        } else { colorDefecto(txt_CVC); }
        
        if (flag == true) {
            etiq_mensajeError.setText("ERROR: compruebe los campos en rojo.");
        }
    }
    
    /**
     * Método que actualiza la interfaz con los nuevos datos del modelo.
     */
    public void actualiza(){
    txt_nombre.setText(mimodelo.getUsuario().getNombre());
    txt_apellidos.setText(mimodelo.getUsuario().getApellidos());
    txt_pais.setText(mimodelo.getUsuario().getPais());;
    txt_email.setText(mimodelo.getUsuario().getEmail());;
    txt_telefono.setText(String.valueOf(mimodelo.getUsuario().getTelefono()));
    txt_propietario.setText(mimodelo.getUsuario().getPropietario());
    txt_numTarjeta.setText(String.valueOf(mimodelo.getUsuario().getNumTarjeta()));
    combo_mes.setSelectedIndex(mimodelo.getUsuario().getMes());
    combo_año.setSelectedItem(String.valueOf(mimodelo.getUsuario().getAño()));
    txt_CVC.setText(String.valueOf(mimodelo.getUsuario().getCVC()));
    
    colorDefecto(txt_nombre);
    colorDefecto(txt_apellidos);
    colorDefecto(txt_pais);
    colorDefecto(txt_email);
    colorDefecto(txt_telefono);
    colorDefecto(txt_propietario);
    colorDefecto(txt_numTarjeta);
    colorDefecto(combo_mes);
    colorDefecto(combo_año);
    colorDefecto(txt_CVC);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Atras;
    private javax.swing.JButton boton_Cancelar;
    private javax.swing.JButton boton_Confirmar;
    private javax.swing.JComboBox combo_año;
    private javax.swing.JComboBox combo_mes;
    private javax.swing.JLabel etiq_Apellidos;
    private javax.swing.JLabel etiq_Fecha;
    private javax.swing.JLabel etiq_Nombre;
    private javax.swing.JLabel etiq_NombreTarj;
    private javax.swing.JLabel etiq_NumeroTarj;
    private javax.swing.JLabel etiq_Pais;
    private javax.swing.JLabel etiq_barra;
    private javax.swing.JLabel etiq_email;
    private javax.swing.JLabel etiq_mensajeError;
    private javax.swing.JLabel etiq_telefono;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_CVC;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numTarjeta;
    private javax.swing.JTextField txt_pais;
    private javax.swing.JTextField txt_propietario;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

}