package reservahotel.vista;

import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.UIManager;
import static reservahotel.ConstantesError.*;
import reservahotel.modelo.Reserva;

/**
 * @author Daniel González Alonso
 * @author Daniel Paredes Santamaría
 */
public class FechaVista extends javax.swing.JFrame {
    private FechaControlador micontrol;
    private Reserva mimodelo;
    
    private final int PERSONA1 = 1;
    private final int PERSONA2 = 2;
    
    /**
     * Constructor con parámetro.
     * @param mimodelo, con el que crearemos la instancia de FechaVista. 
     */
    public FechaVista(Reserva mimodelo) {
        this.mimodelo = mimodelo;
        micontrol = new FechaControlador(this, this.mimodelo);
        
        initComponents();
        actualiza();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        label_diaEntrada = new javax.swing.JLabel();
        label_mesEntrada = new javax.swing.JLabel();
        label_añoEntrada = new javax.swing.JLabel();
        txt_diaEntrada = new javax.swing.JTextField();
        combo_mesEntrada = new javax.swing.JComboBox();
        combo_añoEntrada = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        label_diaSalida = new javax.swing.JLabel();
        txt_diaSalida = new javax.swing.JTextField();
        label_mesSalida = new javax.swing.JLabel();
        label_añoSalida = new javax.swing.JLabel();
        combo_mesSalida = new javax.swing.JComboBox();
        combo_añoSalida = new javax.swing.JComboBox();
        boton_Salir = new javax.swing.JButton();
        boton_Siquiente = new javax.swing.JButton();
        radiobut_1Pers = new javax.swing.JRadioButton();
        radiobut_2Pers = new javax.swing.JRadioButton();
        label_numPersonas = new javax.swing.JLabel();
        etiq_mensajeError = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reserva Hotel");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Entrada"));

        label_diaEntrada.setText("Día");

        label_mesEntrada.setText("Mes");

        label_añoEntrada.setText("Año");

        txt_diaEntrada.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        txt_diaEntrada.setText("1");

        combo_mesEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        combo_añoEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_diaEntrada)
                    .addComponent(txt_diaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_mesEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_mesEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_añoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_añoEntrada))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_diaEntrada)
                    .addComponent(label_mesEntrada)
                    .addComponent(label_añoEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_mesEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_añoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Salida"));

        label_diaSalida.setText("Día");

        txt_diaSalida.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        txt_diaSalida.setText("2");

        label_mesSalida.setText("Mes");

        label_añoSalida.setText("Año");

        combo_mesSalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        combo_añoSalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_diaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_diaSalida))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_mesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_mesSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_añoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_añoSalida))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_diaSalida)
                    .addComponent(label_mesSalida)
                    .addComponent(label_añoSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_mesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_añoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        boton_Salir.setText("Salir");
        boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_SalirActionPerformed(evt);
            }
        });

        boton_Siquiente.setText("Siguiente");
        boton_Siquiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_SiquienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobut_1Pers);
        radiobut_1Pers.setText("1 Persona ");

        buttonGroup1.add(radiobut_2Pers);
        radiobut_2Pers.setText("2 Personas");

        label_numPersonas.setText("Numero de personas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(boton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_Siquiente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiobut_2Pers)
                                    .addComponent(radiobut_1Pers)))
                            .addComponent(label_numPersonas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiq_mensajeError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_numPersonas)
                .addGap(6, 6, 6)
                .addComponent(radiobut_1Pers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobut_2Pers)
                .addGap(18, 18, 18)
                .addComponent(etiq_mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Salir)
                    .addComponent(boton_Siquiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_SalirActionPerformed
        micontrol.salir();
    }//GEN-LAST:event_boton_SalirActionPerformed

    private void boton_SiquienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_SiquienteActionPerformed
        micontrol.comprobar();
    }//GEN-LAST:event_boton_SiquienteActionPerformed

    /**
     * Método que comprueba si el texto que se le pasa puede convertirse a 
     * entero.
     * @return true si sí se puede convertir a entero.
     */
    private boolean checkTipo (String texto){
        try {
            Integer.parseInt(texto);
            return true;
        } catch (NumberFormatException e){
            return false;
        }
    }
    
    // Getters
    /**
     * @return el valor del Día de Entrada en la vista, si los datos
     * no se pudieron convertir a un numero retornará -1
     */
    public int getDiaEntrada (){
        String texto = txt_diaEntrada.getText();
        if (checkTipo(texto)) {
            return Integer.parseInt(texto);
        } else {
            return ERRORGEN;
        }
    }

    /**
     * @return el valor del Mes de Entrada en la vista (el mes va de 0 a 11).
     */
    public int getMesEntrada (){
        return (combo_mesEntrada.getSelectedIndex());
    }
    
    /**
     * @return el valor del Año de Entrada en la vista.
     */
    public int getAñoEntrada (){
        return (Integer.parseInt(combo_añoEntrada.getSelectedItem().toString()));
    }
    
    /**
     * @return el valor del Día de Salida en la vista, si los datos
     * no se pudieron convertir a un numero retornará -1
     */
    public int getDiaSalida (){
        String texto = txt_diaSalida.getText();
        if (checkTipo(texto)) {
            return Integer.parseInt(texto);
        } else {
            return ERRORGEN;
        }
    }
    
    /**
     * @return el valor del Mes de Salida en la vista (el mes va de 0 a 11).
     */
    public int getMesSalida (){
        return (combo_mesSalida.getSelectedIndex());
    }
    
    /**
     * @return el valor del Año de Salida en la vista.
     */
    public int getAñoSalida (){
        return (Integer.parseInt(combo_añoSalida.getSelectedItem().toString()));
    }
    
    /**
     * @return el valor del numero de Personas seleccionado con los 
     * Radio Buttons, ERROR en caso de no haber seleccionado ninguna.
     */
    public int getNumeroPersonas (){
        if (radiobut_1Pers.isSelected()) { return PERSONA1; }
        if (radiobut_2Pers.isSelected()) { return PERSONA2; }
        return ERRORGEN;
    }
    
    //Metodos para cambiar los colores en caso de Error
    /**
     * Método que pone el el objeto de la interfaz seleccionado al color por
     * defecto de la interfaz (color de correcto).
     * @param objeto que queremos cambiar de color.
     */
    public void colorDefecto (JComponent objeto){
        objeto.setBackground(UIManager.getColor ("Panel.background"));
    }
    
    /**
     * Método que pone el objeto de la interfaz seleccionado a rojo 
     * (color de incorrecto).
     * @param objeto que queremos cambiar de color.
     */
    public void colorError (JComponent objeto){
        objeto.setBackground(Color.red);
    }
    
    /**
     * Método que cambia los colores en el campo o campos en los que haya
     * habido un error, los cuales se saben mediante un array de booleanos, 
     * también mostrará un mensaje de error.
     * @param errores, array de booleanos con los distintos errores que pueden
     * suceder en la interfaz.
     */
    public void error (boolean[] errores){
        etiq_mensajeError.setText("");
        
        if (errores[DISPONIBILIDAD]){
            etiq_mensajeError.setText("No hay disponibilidad en las fechas indicadas.");
        }
        
        if (errores[DIAENTRADA]){ colorError(txt_diaEntrada); } 
        else { colorDefecto(txt_diaEntrada); }
        
        if (errores[MESENTRADA]){ colorError(combo_mesEntrada); } 
        else { colorDefecto(combo_mesEntrada); }
        
        if (errores[AÑOENTRADA]){ colorError(combo_añoEntrada); } 
        else { colorDefecto(combo_añoEntrada); }
        
        if (errores[DIASALIDA]){ colorError(txt_diaSalida); } 
        else { colorDefecto(txt_diaSalida); }
        
        if (errores[MESSALIDA]){ colorError(combo_mesSalida); } 
        else { colorDefecto(combo_mesSalida); }
        
        if (errores[AÑOSALIDA]){ colorError(combo_añoSalida); } 
        else { colorDefecto(combo_añoSalida); }
        
        if (errores[FECHAINFACTUAL]){
            colorError(txt_diaEntrada);
            colorError(combo_mesEntrada);
            colorError(combo_añoEntrada);
            etiq_mensajeError.setText("ERROR: Fecha de entrada inferior a la actual.");
        }
        
        if (errores[SALIDAINFENTRADA]){
            colorError(txt_diaSalida);
            colorError(combo_mesSalida);
            colorError(combo_añoSalida);
            etiq_mensajeError.setText("ERROR: Fecha de Salida inferior o igual a la de Entrada.");
        }
        
        if (errores[NUMPERSONAS]){
            colorError(radiobut_1Pers);
            colorError(radiobut_2Pers);
            etiq_mensajeError.setText("ERROR: No ha seleccionado el número de personas.");
        } else {
            colorDefecto(radiobut_1Pers);
            colorDefecto(radiobut_2Pers);
        }
    }
    
    /**
     * Método que actualiza la interfaz con los nuevos datos del modelo.
     */
    public void actualiza(){        
        txt_diaEntrada.setText(String.valueOf(mimodelo.getFechaEntrada().getDia()));
        combo_mesEntrada.setSelectedIndex(mimodelo.getFechaEntrada().getMes());
        combo_añoEntrada.setSelectedItem(String.valueOf(mimodelo.getFechaEntrada().getAño()));
        txt_diaSalida.setText(String.valueOf(mimodelo.getFechaSalida().getDia()));
        combo_mesSalida.setSelectedIndex(mimodelo.getFechaSalida().getMes());
        combo_añoSalida.setSelectedItem(String.valueOf(mimodelo.getFechaSalida().getAño()));
        if (mimodelo.getNumeroPersonas() == PERSONA1) { radiobut_1Pers.setSelected(true); }
        if (mimodelo.getNumeroPersonas() == PERSONA2) { radiobut_2Pers.setSelected(true); }
        
        // Cambiamos al color de correcto
        colorDefecto(txt_diaEntrada);
        colorDefecto(combo_mesEntrada);
        colorDefecto(combo_añoEntrada);
        colorDefecto(txt_diaSalida);
        colorDefecto(combo_mesSalida);
        colorDefecto(combo_añoSalida);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Salir;
    private javax.swing.JButton boton_Siquiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combo_añoEntrada;
    private javax.swing.JComboBox combo_añoSalida;
    private javax.swing.JComboBox combo_mesEntrada;
    private javax.swing.JComboBox combo_mesSalida;
    private javax.swing.JLabel etiq_mensajeError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel label_añoEntrada;
    private javax.swing.JLabel label_añoSalida;
    private javax.swing.JLabel label_diaEntrada;
    private javax.swing.JLabel label_diaSalida;
    private javax.swing.JLabel label_mesEntrada;
    private javax.swing.JLabel label_mesSalida;
    private javax.swing.JLabel label_numPersonas;
    private javax.swing.JRadioButton radiobut_1Pers;
    private javax.swing.JRadioButton radiobut_2Pers;
    private javax.swing.JTextField txt_diaEntrada;
    private javax.swing.JTextField txt_diaSalida;
    // End of variables declaration//GEN-END:variables
}