package reservahotel.vista;

import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.UIManager;
import static reservahotel.ConstantesError.*;
import reservahotel.modelo.Reserva;

/**
 * @author Daniel González Alonso
 * @author Daniel Paredes Santamaría
 */
public class HabitacionVista extends javax.swing.JFrame {
    private HabitacionControlador micontrol;
    private Reserva mimodelo;
    
    private final int INDIVIDUAL = 1;
    private final int DOBLE = 2;
    private final int DOBLEUSOIND = 3;
    private final int SUPERIOR = 4;
    private final int SUITE = 5;
    
    /**
     * Constructor con parámetro.
     * @param mimodelo, con el que crearemos la instancia de HabitaciónVista. 
     */
    public HabitacionVista(Reserva mimodelo) {
        this.mimodelo = mimodelo;
        micontrol = new HabitacionControlador(this, this.mimodelo);
        
        initComponents();
        actualiza();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radiobut_Individual = new javax.swing.JRadioButton();
        radiobut_Doble = new javax.swing.JRadioButton();
        radiobut_DobleUsoInd = new javax.swing.JRadioButton();
        radiobut_Superior = new javax.swing.JRadioButton();
        radiobut_Suite = new javax.swing.JRadioButton();
        combo_Pension = new javax.swing.JComboBox();
        boton_Cancelar = new javax.swing.JButton();
        boton_Siguiente = new javax.swing.JButton();
        boton_Atras = new javax.swing.JButton();
        etiq_mensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reserva Hotel");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Habitación"));

        buttonGroup1.add(radiobut_Individual);
        radiobut_Individual.setText("Individual");

        buttonGroup1.add(radiobut_Doble);
        radiobut_Doble.setText("Doble");

        buttonGroup1.add(radiobut_DobleUsoInd);
        radiobut_DobleUsoInd.setText("Doble de uso individual");

        buttonGroup1.add(radiobut_Superior);
        radiobut_Superior.setText("Superior");

        buttonGroup1.add(radiobut_Suite);
        radiobut_Suite.setText("Suite");

        combo_Pension.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pensión (no seleccionable)", "SA", "AD", "MP", "PC" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobut_DobleUsoInd)
                            .addComponent(radiobut_Superior)
                            .addComponent(radiobut_Suite))
                        .addGap(0, 251, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobut_Individual)
                            .addComponent(radiobut_Doble))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo_Pension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radiobut_Individual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobut_Doble))
                    .addComponent(combo_Pension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobut_DobleUsoInd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobut_Superior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobut_Suite)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boton_Cancelar.setText("Cancelar");
        boton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CancelarActionPerformed(evt);
            }
        });

        boton_Siguiente.setText("Siguiente");
        boton_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_SiguienteActionPerformed(evt);
            }
        });

        boton_Atras.setText("← Atrás");
        boton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(boton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiq_mensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(boton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(boton_Atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiq_mensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Cancelar)
                    .addComponent(boton_Siguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AtrasActionPerformed
        micontrol.atras();
    }//GEN-LAST:event_boton_AtrasActionPerformed

    private void boton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CancelarActionPerformed
        micontrol.cancelar();
    }//GEN-LAST:event_boton_CancelarActionPerformed

    private void boton_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_SiguienteActionPerformed
        micontrol.siguiente();
    }//GEN-LAST:event_boton_SiguienteActionPerformed
    
    // Getters
    /**
     * @return la habitacion seleccionada, 0 en caso de no haber seleccionado
     * ninguna.
     */
    public int getHabitacion (){
        if (radiobut_Individual.isSelected()) { return INDIVIDUAL; }
        if (radiobut_Doble.isSelected()) { return DOBLE; }
        if (radiobut_DobleUsoInd.isSelected()) { return DOBLEUSOIND; }
        if (radiobut_Superior.isSelected()) { return SUPERIOR; }
        if (radiobut_Suite.isSelected()) { return SUITE; }
        return ERRORGEN;
    }
    
    /**
     * @return la pensión seleccionada.
     */
    public int getPension (){
        return combo_Pension.getSelectedIndex();
    }
    
    /**
     * Método que pone el el objeto de la interfaz seleccionado al color por
     * defecto de la interfaz (color de correcto).
     * @param objeto que queremos cambiar de color.
     */
    public void colorDefecto (JComponent objeto){
        objeto.setBackground(UIManager.getColor ("Panel.background"));
    }
    
    /**
     * Método que pone el objeto de la interfaz seleccionado a rojo 
     * (color de incorrecto).
     * @param objeto que queremos cambiar de color.
     */
    public void colorError (JComponent objeto){
        objeto.setBackground(Color.red);
    }
    
    /**
     * Método que cambia los colores en el campo o campos en los que haya
     * habido un error, los cuales se saben mediante un array de booleanos, 
     * también mostrará un mensaje de error.
     * @param errores, array de booleanos con los distintos errores que pueden
     *      suceder en la interfaz.
     */
    public void error (boolean[] errores){
        etiq_mensajeError.setText("");
        
        if (errores[HABITACION]){
            etiq_mensajeError.setText("ERROR: No ha seleccionado ninguna habitación.");
        }
        
        if (errores[PENSION]){
            colorError(combo_Pension);
            etiq_mensajeError.setText("ERROR: No ha seleccionado ninguna pensión.");
        } else { colorDefecto(combo_Pension); }
    }
    
    /**
     * Método que deshabilita el objeto pasado para que no pueda seleccionarlo
     * y lo pone a un color más claro para poder identificarlo.
     * @param objeto que queremos deshabilitar
     */
    public void noSeleccionable(JComponent objeto){
        objeto.setForeground(Color.LIGHT_GRAY);
        objeto.setEnabled(false);
    }
    
    /**
     * Método que actualiza la interfaz con los datos del modelo, y segun 
     * el numero de Personas inhabilita la selección de unas habitaciones 
     * u otras.
     */
    public void actualiza(){
        if (mimodelo.getNumeroPersonas() == 1){
            noSeleccionable(radiobut_Doble);
        } else {
            noSeleccionable(radiobut_Individual);
            noSeleccionable(radiobut_DobleUsoInd);
        }
        
        if (mimodelo.getHabitacion() == INDIVIDUAL) { radiobut_Individual.setSelected(true); }
        if (mimodelo.getHabitacion() == DOBLE) { radiobut_Doble.setSelected(true); }
        if (mimodelo.getHabitacion() == DOBLEUSOIND) { radiobut_DobleUsoInd.setSelected(true); }
        if (mimodelo.getHabitacion() == SUPERIOR) { radiobut_Superior.setSelected(true); }
        if (mimodelo.getHabitacion() == SUITE) { radiobut_Suite.setSelected(true); }
        combo_Pension.setSelectedIndex(mimodelo.getPension());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Atras;
    private javax.swing.JButton boton_Cancelar;
    private javax.swing.JButton boton_Siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combo_Pension;
    private javax.swing.JLabel etiq_mensajeError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radiobut_Doble;
    private javax.swing.JRadioButton radiobut_DobleUsoInd;
    private javax.swing.JRadioButton radiobut_Individual;
    private javax.swing.JRadioButton radiobut_Suite;
    private javax.swing.JRadioButton radiobut_Superior;
    // End of variables declaration//GEN-END:variables
}